### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by mojo2012** [wizawu/tyrian#26]
Hi,

is there a way to actually debug the code (breakpoints, stepping through, inspection) using vscode?

I'm pleased to see how smooth it runs. But without a proper way to debug it's not really fun.

**Comment by wizawu** [comment]
I am working on the next version (moving to graalvm node). After that you can you debug the code in the node.js way.

**Comment by mojo2012** [comment]
That is awesome! How far are you? Are we speaking weeks, months or longer?

**Comment by wizawu** [comment]
I believe it may just take days, since it's Chinese New Year holiday now and I can work on this project day and night :smile:

**Comment by mojo2012** [comment]
any news on this?

**Comment by wizawu** [comment]
A beta version by this weekend.

**Comment by wizawu** [comment]
Check out 
- https://www.npmjs.com/package/tyrian/v/9.0.0-beta.1
- https://github.com/wizawu/tyrian/tree/dev/tests

Please report any bug or feature you want. I will update the user guide later today.

**Comment by mojo2012** [comment]
Sorry for the late reply. I can't seem to get the latest version to run.
When I invoke `tyrian` it immediately crashes with this log:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'glob'
Require stack:
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/install.js
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/index.js
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/main.js
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/bin/tyrian
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/install.js:72:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/install.js',
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/index.js',
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/main.js',
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/bin/tyrian'
  ]
}
```

It seems that the dependencies are not set up correctly.

If I run npm i in the node_modules/tyrian I get this:
```
Require stack:
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/parser/javap/JavapLexer.js
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/parser/index.js
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/install.js
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/index.js
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/main.js
- /Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/bin/tyrian
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/parser/javap/JavapLexer.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/parser/javap/JavapLexer.js',
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/parser/index.js',
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/install.js',
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/commands/index.js',
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/dist/main.js',
    '/Users/matthias/Projekte/Git/1c-demo/node_modules/tyrian/bin/tyrian'
  ]
}
```

Any idea how to fix this.
Also how would I connect the debugger? Can I pass --inspect to the graalvm node runtime?

**Comment by wizawu** [comment]
I found the similar errors and just [fixed it](https://github.com/wizawu/tyrian/commit/60b8a0b810b21af3c0dc634a15da2c0e9c841627#diff-fb19954ad9c19d5004b1b36f4322497cb03dce0b6cf3377e2cf16873950c71a8R49).

Please try `tyrian@9.0.0-rc3`. And if the problem still exists, please upload your demo source to GitHub.

Sorry for the inconvenience.

**Comment by mojo2012** [comment]
Unfortunately I still doesn't work. There is not much to upload. To reproduce:
```
» npm -g i tyrian@9.0.0-rc4

added 131 packages, and audited 132 packages in 5s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
» npm -g list
/usr/local/lib
├── @ionic/cli@6.12.4
├── @kps-common/kps-rmp-cli@1.0.422
├── @nestjs/cli@7.6.0
├── ansi-regex@5.0.0
├── ansi-styles@5.2.0
├── eslint-visitor-keys@2.0.0
├── eslint@7.22.0
├── file-entry-cache@6.0.1
├── npm@7.7.6
├── parcel@1.12.4
├── ts-node@9.0.0
├── typescript@4.1.3
├── tyrian@9.0.0-rc4
└── yarn@1.21.1

cln-m-04020 :: Projekte/privat/typrian-demo
» ls
cln-m-04020 :: Projekte/privat/typrian-demo
» tyrian init
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'antlr4/index'
Require stack:
- /usr/local/lib/node_modules/tyrian/dist/parser/javap/JavapLexer.js
- /usr/local/lib/node_modules/tyrian/dist/parser/index.js
- /usr/local/lib/node_modules/tyrian/dist/commands/install.js
- /usr/local/lib/node_modules/tyrian/dist/commands/index.js
- /usr/local/lib/node_modules/tyrian/dist/main.js
- /usr/local/lib/node_modules/tyrian/bin/tyrian
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/tyrian/dist/parser/javap/JavapLexer.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/tyrian/dist/parser/javap/JavapLexer.js',
    '/usr/local/lib/node_modules/tyrian/dist/parser/index.js',
    '/usr/local/lib/node_modules/tyrian/dist/commands/install.js',
    '/usr/local/lib/node_modules/tyrian/dist/commands/index.js',
    '/usr/local/lib/node_modules/tyrian/dist/main.js',
    '/usr/local/lib/node_modules/tyrian/bin/tyrian'
  ]
}
cln-m-04020 :: Projekte/privat/typrian-demo
»

I just installed tyrian globally, cerated a new directory and tried used `tyrian init`. This already fails without doing anything. It seems that the dependencies are just not setup properly. Shouldn't it install `antl4` as a dependendy on `nom install`?

**Comment by wizawu** [comment]
It's the problem of antlr4@4.9.x. Actually I'd downgraded the version of antlr before, but it seemed your npm didn't honer the `package-lock.json` file. Please try `tyrian@9.0.2`, which I just fixed the `package.json` also.

**Comment by mojo2012** [comment]
I managed to get my demo working again (hello world). The setup process needs improvement though:
* Why not detect graalvm automatically?
* The tsconfig.json has absolute file paths set. Relative paths would better
* Furthermore as a java dev I'd love to see better default settings in the tsconfig set (eg. enable all strict-settings), setup path prefixes (take a look at one of my setups: https://github.com/mojo2012/whatsnear/blob/main/frontend/tsconfig.json)
* `tyrian init` should also setup a `src` folder and a default hello world `main.ts`, and proper npm start and build scripts

Now I'll try to get the debugger running :-)

**Comment by wizawu** [comment]
> the default setup always adds caffeine and gson to the gradle.build dependencies, although they are not set in my mvnDependencies

Sorry but I can't reproduce this.

**Comment by mojo2012** [comment]
Yeah weird, now I can't reproduce it either. Yesterday I was able to reproduce it repeatedly. Maybe it was a vscode hickup ...

**Comment by wizawu** [comment]
>  Why not detect graalvm automatically?

There're too many use cases.

* I use OpenJ9 (JDK 8) as my default JVM, so I won't put GraalVM bin in `PATH` env.
* For some other people, they might consider using tyrian with nashorn.

So I prefer no default JVM option.
