### ISSUE TITLE
tyrian init have this error

### ISSUE THREAD

**Issue by lixiangsheng2018** [wizawu/tyrian#35]
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/lxs/.nvm/versions/node/v12.22.10/lib/node_modules/tyrian/node_modules/antlr4/src/antlr4/index.js
require() of ES modules is not supported.
require() of /home/lxs/.nvm/versions/node/v12.22.10/lib/node_modules/tyrian/node_modules/antlr4/src/antlr4/index.js from /home/lxs/.nvm/versions/node/v12.22.10/lib/node_modules/tyrian/dist/parser/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/lxs/.nvm/versions/node/v12.22.10/lib/node_modules/tyrian/node_modules/antlr4/src/antlr4/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/lxs/.nvm/versions/node/v12.22.10/lib/node_modules/tyrian/node_modules/antlr4/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lxs/.nvm/versions/node/v12.22.10/lib/node_modules/tyrian/dist/parser/index.js:26:34)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by wizawu** [comment]
周末回你哈

**Comment by wizawu** [comment]
/home/lxs/.nvm/versions/node/v12.22.10/lib/node_modules/tyrian/node_modules/antlr4/package.json
这个文件的内容复制出来我看一下
