### ISSUE TITLE
Unable to build the http-server example

### ISSUE THREAD

**Issue by ali-baykal** [wizawu/tyrian#37]
Hi,

I was trying to build the example you provide in the repo by running `tyrian build ./src/main.ts` from within the http-server folder. But I got following error

```
Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/dist/parser/index.js:26
const antlr4_1 = __importDefault(require("antlr4"));
                                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/node_modules/antlr4/src/antlr4/index.js from /Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/dist/parser/index.js not supported.
Instead change the require of /Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/node_modules/antlr4/src/antlr4/index.js in /Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/dist/parser/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/dist/parser/index.js:26:34)
    at Object.<anonymous> (/Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/dist/commands/install.js:44:29)
    at Object.<anonymous> (/Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/dist/commands/index.js:8:35)
    at Object.<anonymous> (/Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/dist/main.js:29:36)
    at Object.<anonymous> (/Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/bin/tyrian:3:1) {
  code: 'ERR_REQUIRE_ESM'
}
```
My environment is as such
```
java --version                
openjdk 18.0.1.1 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

```
gradle --version

------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (Homebrew 16.0.1+0)
OS:           Mac OS X 12.4 x86_64

```

```
node --version
v18.2.0
```

**Comment by rikardbq** [comment]
I also run in to the same error whenever i try to "tyrian init" in command line

```
java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

```
gradle --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/share/java/groovy-all.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.21
Ant:          Apache Ant(TM) version 1.10.12 compiled on January 17 1970
JVM:          11.0.16 (Ubuntu 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OS:           Linux 5.15.0-25-generic amd64
```

```
 node -v
v16.16.0
```

**Comment by wizawu** [comment]
Please try version 9.3.0, which antlr4 is the latest version.

**Comment by ali-baykal** [comment]
Hi @wizawu,
I did the update and tried again. Unfornuttaly I can not confirm a fix. I still get the same error. I made sure to have installed the correct versions of tyrian and antlr4 by looking into their package.json.

```js
// /Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/package.json
{
  "name": "tyrian",
  "version": "9.3.0",
  "repository": "github:wizawu/tyrian",
  "license": "MIT",
  "bin": "bin/tyrian",
  "scripts": {
    "antlr": "cd src/parser/javap && antlr4 -Dlanguage=JavaScript -visitor Javap.g4",
    "build": "tsc -p .",
    "watch": "tsc -p . -w",
    "types": "test $JAVAP && node src/jdk/allclasses.js",
    "test": "cd test && mocha --timeout 5000 unit/*.js unit/**/*.js",
    "lint": "eslint --ignore-pattern '/src/parser/javap/*' --fix src test/unit",
    "lint:types": "eslint --ext .ts --fix @types"
  },
  "dependencies": {
    "antlr4": "4.10.*",
    "chalk": "^4.1.0",
    "commander": "^6.2.0",
    "dotenv": "^10.0.0",
    "glob": "^7.1.6",
    "jszip": "^3.7.0",
    "prompts": "^2.4.0",
    "redent": "^3.0.0",
    "ts-loader": "^8.0.17",
    "typescript": "4.7.*",
    "webpack": "^5.24.2",
    "which": "^2.0.2"
  },
  "devDependencies": {
    "@types/antlr4": "^4.7.2",
    "@types/glob": "^7.1.3",
    "@types/node": "^12.19.9",
    "@typescript-eslint/eslint-plugin": "^4.9.1",
    "@typescript-eslint/parser": "^4.9.1",
    "eslint": "^7.15.0",
    "mocha": "^9.2.0",
    "node-html-parser": "^2.0.2"
  }
}
```
```js
// /Users/abaykal/.nvm/versions/node/v18.2.0/lib/node_modules/tyrian/node_modules/antlr4/package.json
{
  "name": "antlr4",
  "version": "4.10.1",
  "type": "module",
  "description": "JavaScript runtime for ANTLR4",
  "main": "src/antlr4/index.js",
  "repository": "antlr/antlr4.git",
  "keywords": [
    "lexer",
    "parser",
    "antlr",
    "antlr4",
    "grammar"
  ],
  "license": "BSD-3-Clause",
  "bugs": {
    "url": "https://github.com/antlr/antlr4/issues"
  },
  "homepage": "https://github.com/antlr/antlr4",
  "devDependencies": {
    "@babel/preset-env": "^7.16.11",
    "babel-loader": "^8.2.4",
    "eslint-plugin-es5": "^1.5.0",
    "eslint-webpack-plugin": "^3.1.1",
    "glob-parent": "^6.0.2",
    "jasmine": "^4.0.2",
    "jasmine-spec-reporter": "^7.0.0",
    "minimist": "^1.2.6",
    "webpack": "^5.66.0",
    "webpack-cli": "^4.9.1"
  },
  "scripts": {
    "build": "webpack",
    "test": "jasmine"
  },
  "engines": {
    "node": ">=14"
  },
  "browser": {
    "fs": false,
    "net": false,
    "module": false
  }
}
```

**Comment by wizawu** [comment]
The previous dist is built by Node 12. The errors were caused by running tyrian on newer version of Node.

Please install tyrian@11.x and have Node.js >= 14.x installed
